### ISSUE TITLE
fyi electron 4.2.12 is actually the last to work with 10.9

### ISSUE THREAD

**Issue by krackers** [Wowfunhappy/electron-template#1]
just need to polyfill two functions

**Comment by Wowfunhappy** [comment]
Thank you! I will need to do this...

**Comment by Wowfunhappy** [comment]
Yep that just worked, I literally only changed LSMinimumSystemVersion from 10.10 to 10.9. @krackers What were the functions that should be polyfilled?

**Comment by Wowfunhappy** [comment]
Ah, I found at least one, it appears on pages which use system fonts:

```
9/22/24 9:52:44.837 AM Electron Wrapper Helper[74521]: +[NSFont systemFontOfSize:weight:]: unrecognized selector sent to class 0x7fff79853f70
```

**Comment by Wowfunhappy** [comment]
Hmm, might be better off sticking with 3.1.13. In electron 3.1.13, window resizing is smooth, you can drag the window larger and the browser content resizes in realtime, as it would in a real Cocoa app.

In electron 4.2.12, you see a gray window background temporarily before the browser content "catches up" (as it typically does in Chromium Legacy).

I really really want everything to seem as much like a real native mac app as is possible.

**Comment by Wowfunhappy** [comment]
@krackers Do you have a sense of how significant the changes were between Chromium 66 (Electron 3.1.13) and Chromium 69 (electron 4.2.12), specifically with an eye toward webapp compatibility? Is there anything big in Chromium 69 that would make more webapps work, which would not be trivially fixed by adding CoreJS?

I could test every webapp in both versions of Electron, but the point of this template is to make stuff _quickly!_

**Comment by krackers** [comment]
I don't think there is anything significant you cannot polyfill. https://caniuse.com/ is the canonical source of truth and you can see https://caniuse.com/?compare=chrome+66,chrome+69&compareCats=all

Mostly some obscure CSS and Canvas2D stuff, I don't know hard the latter is to polyfill. If you haven't noticed anything it's probably fine.

Given that this seems to be intended for app-ifying local static webpages (as opposed to loading external sites), it should be easy to avoid those.
